[project]
name = "skillboost_local_idx"
version = "0.1.0"
readme = "README.md"
requires-python = ">=3.10"
description="skillboost_local_idx"
dependencies = [
    "requests",
    "weasyprint",
    "pytest",
    "ruff", "reportlab"
    

]
